# config.yaml
# 직접 하이퍼파라미터를 추가하여 관리할 수 있습니다.

memo: |-
    남겨둘 메모가 있다면 여기에.
    여러 줄로도 작성 가능


checkpoint: 'saved/checkpoint/~.pt'   # 예측 시 불러올 모델 경로
seed: 42               # 시드 고정
device: cuda          # 가능한 값 : cpu, cuda, mps
model: MF       # 모델 선택
run_name: 'jinnk0 : MF'
wandb: True                               # wandb 사용 여부
wandb_project: 'lv2.movie_recommendation'  # wandb 프로젝트 이름

model_args:
    MF:
        valid : 1
        inference : True  # 예측 모드 여부 (학습 모드=False, 예측 모드=True)
        alpha : 1  # Regularization 파라미터
        l1 : 0.1  # L1 규제값
        feature_dims : 64  # ALS feature 차원 (hidden dimension)
        output_dir : '../saved/submit/'  # 결과를 저장할 디렉토리
        data_path : '../data/train/'  # 데이터 파일 경로
        epochs : 20
        tfidf_weight : 1



dataset:
    data_path: ./data/train/    # 데이터셋 경로
    ratio: 0.1                  # Train / Vaildation / Test split
    test_prop : 0.2




train:
    epochs: 20                               # 학습 에폭 수
    ckpt_dir: saved/EASE/checkpoint          # 모델 저장 경로
    submit_dir: ../saved/submit            # 예측 저장 경로
    save_best_model: True                    # True: val_loss가 최소인 모델 저장 / False: 모든 모델 저장
    resume: False                            # 이어서 학습할 경우 True
    resume_path: saved/checkpoint/EASE.pt    # 이어서 학습할 모델 경로
