_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
config:
    value: config.yaml
dataloader:
    value:
        batch_size: 250
        data_path: ../
        num_workers: 0
        shuffle: true
dataset:
    value:
        data_path: ../../data/train/
        ratio: 0.1
        save_path: ../../data/BERT4Rec_with_side_info/
        test_prop: 0.2
device:
    value: cuda
lr_scheduler:
    value:
        use: false
memo:
    value: |-
        남겨둘 메모가 있다면 여기에.
        여러 줄로도 작성 가능
model:
    value: BERT4Rec_with_side_info
model_args:
    value:
        BERT4Rec_with_side_info:
            device: cuda
            dropout_rate: 0.5
            hidden_units: 50
            max_len: 50
            num_heads: 1
            num_layers: 2
            num_workers: 1
optimizer:
    value:
        args:
            amsgrad: false
            lr: 0.0007222579954275256
            weight_decay: 9.537626692587012e-05
        type: Adam
other_params:
    value:
        args:
            anneal_cap: 0.5
            log_interval: 100
            total_anneal_steps: 200000
predict:
    value: false
run_name:
    value: 'jay : BERT4Rec_with_side_info'
seed:
    value: 0
train:
    value:
        batch_size: 128
        ckpt_dir: ../../saved/checkpoint
        epochs: 100
        log_dir: ../../saved/log
        lr: 0.001
        mask_prob: 0.15
        resume: false
        save_best_model: true
        submit_dir: ../../saved/submit
wandb:
    value: true
wandb_project:
    value: lv2.movie_recommendation
