# config.yaml
# EASER 모델 학습 및 평가를 위한 설정 파일
# 필요에 따라 하이퍼파라미터를 조정하세요.

memo: |-
    EASER 모델 학습 및 평가를 위한 설정 파일
    필요에 따라 하이퍼파라미터를 조정하세요.

checkpoint: 'saved/EASER/checkpoint/EASER.pth'  # 예측 시 불러올 모델 경로
seed: 99                                        # 시드 고정
predict: True
device: cuda                                    # 가능한 값: cpu, cuda, mps
model: EASER                                    # 모델 선택
run_name: 'EASER : Movie Recommendation'
wandb: True                                     # wandb 사용 여부
wandb_project: 'lv2.movie_recommendation'       # wandb 프로젝트 이름


model_args:     # EASER 모델에 해당하는 파라미터
    EASER:
        threshold: 3500
        lambdaBB: 500
        lambdaCC: 10000
        rho: 50000
        epochs: 100

dataset:
    data_path: ./data/train/                      # 데이터셋 경로
    ratio: 0.1                                  # Train / Validation / Test split
    valid_samples: 10                           # Validation 데이터 수

dataloader:
    data_path: src/  # 데이터 load 경로
    shuffle: True                                # 학습 데이터 셔플 여부
    num_workers: 0                               # 멀티프로세서 수



train:
    ckpt_dir: saved/EASER/checkpoint/             # 모델 저장 경로
    submit_dir: saved/EASER/submit/               # 예측 저장 경로
    predict_dir: saved/EASER/predict/          # matrix 저장 경로
    save_best_model: True                        # True: val_loss가 최소인 모델 저장
    resume: False                                # 이어서 학습할 경우 True
    resume_path: saved/EASER/checkpoint/EASER.pth  # 이어서 학습할 모델 경로
    K: 10                                        # 추천 상위 K

other_params:
    args:
        log_interval: 100                        # 로그 간격

output_dir: saved/EASER/output/  # 결과 저장 경로
