model:
  hidden_units: 50 
  num_heads: 1
  num_layers: 2
  dropout_rate: 0.5
  max_len: 50
 
train:
  batch_size: 128
  num_epochs: 100
  learning_rate: 0.001
  num_workers: 1
  device: "cuda"
  data_path: "data/train/train_ratings.csv"

eval:
  num_item_sample: 100 
  num_user_sample: 1000