checkpoint: /data/ephemeral/home/src/RecVAE/saved/RecVAE/checkpoint/20241127_145459_RecVAE_best.pt
seed: 1111
predict: False
device: cuda
model: RecVAE
run_name: 'eun : RecVAE'
wandb: False                                # wandb 사용 여부
wandb_project: 'lv2.movie_recommendation'  # wandb 프로젝트 이름

model_args:     # model에 해당하는 파라미터만 실질적으로 사용됩니다.
    RecVAE:
        hidden_dim: 600
        latent_dim: 200
        input_dim: 6807

dataset:
    data_path: /data/ephemeral/home/data/train/    # 데이터셋 경로
    ratio: 0.1                  # Train / Vaildation / Test split
    test_prop : 0.2

dataloader:
    device: cuda
    data_path: /data/ephemeral/home/src/    # 데이터 load 경로(개인 폴더 경로로 설정해야함)
    batch_size: 500         # 배치 사이즈
    shuffle: True           # 학습 데이터 셔플 여부
    num_workers: 0          # 멀티프로세서 수. 0: 메인프로세서만 사용

optimizer:
    type: Adam      # 사용가능한 optimizer: torch.optim.Optimizer 클래스 (https://pytorch.org/docs/stable/optim.html#algorithms)
    args:           # 사용하고자 하는 클래스의 파라미터를 참고하여 추가해주시면 되며, 관계가 없는 파라미터는 무시됩니다.
        lr: 1e-4             # 예) 모든 옵티마이저에서 사용되는 학습률
        weight_decay: 0     # 예) Adam 등 / L2 정규화 가중치
        amsgrad: False                           # 예) Adam 등 / amsgrad 사용 여부

train:
    epochs: 3
    not_alternating: False
    log_dir: saved/RecVAE/log                  # 로그 저장 경로
    ckpt_dir: saved/RecVAE/checkpoint    # 모델 저장 경로
    submit_dir: saved/RecVAE/submit            # 예측 저장 경로
    save_dir: 
    save_best_model: False               # True: val_loss가 최소인 모델 저장 / False: 모든 모델 저장
    resume: False                               # 이어서 학습할 경우 True
    resume_path: saved/checkpoint/RecVAE.pt    # 이어서 학습할 모델 경로