# RecBole 데이터를 구성하는 yaml
save_dataloaders: True
data_path: '../data/train/'
dataset: 'movie_rec'

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp

load_col:
    inter: [user_id, item_id, timestamp]

user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"
val_interval:
    timestamp: "[97830000, inf)"