# config.yaml
# 직접 하이퍼파라미터를 추가하여 관리할 수 있습니다.

memo: |-
    남겨둘 메모가 있다면 여기에.
    여러 줄로도 작성 가능


checkpoint: 'saved/checkpoint/EASE.pt'   # 예측 시 불러올 모델 경로
seed: 0               # 시드 고정
device: cuda          # 가능한 값 : cpu, cuda, mps
model: EASE       # 모델 선택
run_name: 'choi : EASE'
wandb: True                               # wandb 사용 여부
wandb_project: 'lv2.movie_recommendation'  # wandb 프로젝트 이름


model_args:     # model에 해당하는 파라미터만 실질적으로 사용됩니다.
    EASE:
        lambda: 300


dataset:
    data_path: ./data/train/    # 데이터셋 경로
    ratio: 0.1                  # Train / Vaildation / Test split
    test_prop : 0.2


dataloader:
    data_path: ./   # 데이터 load 경로(개인 폴더 경로로 설정해야함)
    batch_size: 250         # 배치 사이즈
    shuffle: True           # 학습 데이터 셔플 여부
    num_workers: 0          # 멀티프로세서 수. 0: 메인프로세서만 사용




train:
    ckpt_dir: saved/EASE/checkpoint/          # 모델 저장 경로
    submit_dir: saved/EASE/submit/            # 예측 저장 경로
    predict_dir: saved/EASE/predict/          # matrix 저장 경로
    save_best_model: True                    # True: val_loss가 최소인 모델 저장 / False: 모든 모델 저장
    resume: False                            # 이어서 학습할 경우 True
    resume_path: saved/checkpoint/EASE.pt    # 이어서 학습할 모델 경로
